#!/bin/bash

exec docker run \
  -d \
  -u jenkins:999 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v jenkins_home:/var/jenkins_home \
  -v "$HOME":/home \
  -e VIRTUAL_HOST=ci.delta.chat \
  -e VIRTUAL_PORT=8080 \
  --restart always \
  --name jenkins \
  jenkinsci/blueocean
